### ISSUE TITLE
nn_NO or sv_SE?

### ISSUE THREAD

**Issue by plastikschnitzer** [mageplaza/magento-2-norwegian-nynorsk-language-pack#1]
I think the composer install manual command must be updated, you write 

`php bin/magento setup:static-content:deploy sv_SE`

but I think it should be:

`php bin/magento setup:static-content:deploy nn_NO`

**Comment by u12206050** [comment]
#4 Created pull request with fixed documentation

**Comment by zebeel** [comment]
It fixed in current version.

**Comment by wireless-r** [comment]
It should be nb_NO. The Norwegian language has two written standards, Bokmål (nb_NO) and Nynorsk (nn_NO). This translation is written in Bokmål.

**Comment by MyoDaisy** [comment]
We have modified the code to **nb_NO.** Thank you for your feedback.
