### ISSUE TITLE
Invalid language code "no_NO"

### ISSUE THREAD

**Issue by wireless-r** [mageplaza/magento-2-norwegian-nynorsk-language-pack#5]
When deploying static content, it gives the error that *no_NO* is an invalid value.

>`no_NO argument has invalid value, please run info:language:list for list of available locales`

The language code should be nb_NO. The Norwegian language has two written standards (Bokmål and Nynorsk). This translation is written in Bokmål.

**Comment by MyoDaisy** [comment]
We have modified the code to **nb_NO.** Thank you for your feedback.
