### ISSUE TITLE
Phrase not translated.

### ISSUE THREAD

**Issue by wireless-r** [mageplaza/magento-2-norwegian-nynorsk-language-pack#6]
Hi. The word "or" doesn't get translated.

![bilde](https://user-images.githubusercontent.com/28116634/51980046-1f908900-248f-11e9-93b4-5db50b8bc8f9.png)

Template `vendor\magento\module-customer\view\frontend\templates\account\link\authorization.phtml`

```html
<li class="authorization-link" data-label="<?= $block->escapeHtml(__('or')) ?>">
```
This line is in .csv file. It should be correct. Why doesn't it get translated?

```csv
or,eller,module,Magento_Customer
```

**Comment by MyoDaisy** [comment]
Please try adding it to the **no_NO.csv** file and delete **js-translation.json** file in your theme.
Path for example: **pub/static/frontend/Magento/luma/nb_NO/js-translation.json**
Then deploy your site again.
